### ISSUE TITLE
QWIIC / I2C setup is non-obvious

### ISSUE THREAD

**Issue by zyphlar** [sparkfun/SparkFun_ESP32_Qwiic_Pro_Mini#3]
I wasted 2 hours debugging why QWIIC / I2C was failing to find anything after following the ESP32 QWIIC instructions and example instructions for the BME688 and WM8960. I found the answer here:

https://forum.sparkfun.com/viewtopic.php?f=105&t=61109&p=248274&hilit=qwiic+esp32#p248274

It needs to be a lot more obvious that these lines have to be added to sketches in order to function, considering that this board is purchased for the express purpose of using with QWIIC stuff. Users of QWIIC are sacrificing the speed of SPI/etc for the convenience of a nearly plug-n-play ecosystem, so that takes some extra documentation and library work:

```
int pin_SDA = 15;
int pin_SCL = 5;

void setup() {
  Wire.begin(pin_SDA, pin_SCL); //SDA, SCL
```

**Comment by nseidle** [comment]
Sorry for the hassle. The Examples are located here: https://github.com/sparkfun/SparkFun_ESP32_Qwiic_Pro_Mini/tree/main/Firmware

I'll ask the docs team to add an I2C and possibly a SPI example.

**Comment by zyphlar** [comment]
It needs to be linked from here, since these pages are where people go when they buy and begin using the device. I got Blink working just fine on the ESP32 Qwiic, but then I'm left hanging by the website and have to start digging deep to figure out where else proper code might be found. New users won't know that there's 2-3 different places to find relevant code without spending an hour clicking and searching fruitlessly. https://docs.sparkfun.com/SparkFun_ESP32_Qwiic_Pro_Mini/arduino_example/#uploading-code
